version: '3.5'

services:
  localstack:
    image: localstack/localstack
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - EDGE_PORT=4566
      - SERVICES=kinesis, dynamodb, cloudwatch
    ports:
      - '4566:4566'
    volumes:
      - localstack:/tmp/localstack
      - './setup-localstack.sh:/docker-entrypoint-initaws.d/setup-localstack.sh'

volumes:
  localstack: